import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import resume from "../public/resumeEx.png"
const Home: NextPage = () => {
  return (
    <div className=" text-white ">
      <Head>
        <title>Resume3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex flex-col items-center pt-60 gap-2 h-screen">
        <div className="flex text-4xl gap-2">Resume <p className="text-regal-purple font-weight-400">Building</p></div>
        <p className="text-4xl ">Made Simple</p>
        <p className='text-gray-300'>Remote3 is a web3 based Resume buiding website</p>
        <button className='px-4 py-2 rounded text-black bg-regal-purple'>Create Now</button>
      </div>
      <div className=' flex justify-center'>
        <div className='mx-60 w-fit   rounded-lg flex flex-col items-center pb-20 h-screen'>
          <p className="text-2xl font-['Open_sans'] font-bold tracking-wide">Resume Template</p>
          <p className='mt-2 text-lg'>As of now this is the template you can go and directly build your resume in create page by paying 0.5$ of matic.</p>
          <p className='text-lg'>We are going to add more templates soon...</p>
          <img src="/resumeEx.png" alt="resume" className="rounded-sm h-full w-full mt-5"/>
        </div>
      </div>
      <div className='p-5 flex justify-center border-[#8D72E1] border-t-2 font-["Lobster"]'>
        <p className='tracking-widest text-lg italic '>Built by <button className="tracking-widest text-lg  underline decoration-[#8D72E1] underline-offset-6" onClick={()=>window.open("https://twitter.com/dineshaitham1")}>Dinesh Aitham</button></p>
      </div>
    </div>
  )
}

export default Home
