import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import resume from "../public/resumeEx.png"
import { useRouter } from 'next/router'
const Home: NextPage = () => {
  const router = useRouter()
  return (
    <div className=" text-white ">
      <Head>
        <title>Resume3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex flex-col items-center pt-32 gap-2 h-screen">
        <div className="flex text-4xl gap-2">Resume <p className="text-regal-purple font-weight-400">Building</p></div>
        <p className="text-4xl ">Made Simple</p>
        <p className='text-gray-300'>Resume3 is a web3 based Resume buiding website powered by IPFS / Filecoin, Polygon, Chainlink and Spheron</p>
        <button className='px-4 py-2 rounded text-black bg-regal-purple mt-2' onClick={()=>router.push("/create")}>Create Now</button>
        <p className='mt-8 text-xl tracking-wide'>How to make resume in Resume3</p>
        <div className='flex justify-evenly w-3/4 mt-4'>
          <div className='flex flex-col gap-1 items-center w-1/5 p-10 hover:bg-[#b59cff] hover:text-black rounded-lg border-2 border-[#8D72E1]'>
            <p className='text-lg underline underline-offset-2'>Step 1</p>
            <p className='text-lg'>Choosing </p>
            <p className='tracking-wide'>Right now there is only one template So Head to create page</p>
          </div>
          <div className='flex flex-col gap-1 items-center w-1/5 p-10 hover:bg-[#b59cff] hover:text-black rounded-lg border-2 border-[#8D72E1]'>
            <p className='text-lg underline underline-offset-2'>Step 2</p>
            <p className='text-lg'>Filling</p>
            <p className='tracking-wider'>Fill the neccessary details including your name to your experience</p>
          </div>
          <div className='flex flex-col gap-1 items-center w-1/5 p-10 hover:bg-[#b59cff] hover:text-black rounded-lg border-2 border-[#8D72E1]'>
            <p className='text-lg underline underline-offset-2'>Step 3</p>
            <p className='text-lg'>Creating</p>
            <p className='tracking-wide'>Click on create button and Pay the 0.5$ of matic and wait for the resume to be created</p>
          </div>
        </div>
      </div>
      <div className=' flex justify-center'>
        <div className='mx-60 w-fit   rounded-lg flex flex-col items-center pb-20 h-screen'>
          <p className="text-2xl font-['Open_sans'] font-bold tracking-wide">Resume Template</p>
          <p className='mt-2 text-lg'>As of now this is the template you can go and directly build your resume in create page by paying 0.5$ of matic.</p>
          <p className='text-lg'>We are going to add more templates soon...</p>
          <img src="/resumeEx.png" alt="resume" className="rounded-sm h-full w-full mt-5"/>
        </div>
      </div>
      <div className='p-5 flex justify-center border-[#8D72E1] border-t-2 font-["Lobster"]'>
        <p className='tracking-widest text-lg italic '>Built by <button className="tracking-widest text-lg  underline decoration-[#8D72E1] underline-offset-6" onClick={()=>window.open("https://twitter.com/dineshaitham1")}>Dinesh Aitham</button></p>
      </div>
    </div>
  )
}

export default Home
