import Head from "next/head"
import Image from "next/image"
import {HiOutlineMail} from 'react-icons/hi'
import {FiPhone} from 'react-icons/fi'
import {CiTwitter} from 'react-icons/ci'
import {FiTwitter} from 'react-icons/fi'
import {AiFillGithub} from 'react-icons/ai'
import {BiLinkExternal} from 'react-icons/bi'
export default function Resume() {

    const skills = ["JavaScript","Soliidty","React","Next.js","Hardhat","Truffle","Web3.js","Ethers.js","TypeScript","Truffle","Java","Python"]

    return (
        <div className=" text-black bg-white h-screen">
            <Head>
                <title>Resume3</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex border-b-2 border-black py-8 px-20 justify-between gap-5 ">
                <div className="flex gap-4">
                    <Image src="/profile.png" alt="profile" width={100} height={100}  className="rounded-xl"/>
                    <div className="">
                        <p className="text-2xl font-bold">Dinesh Aitham</p>
                        <p className="text-gray-600">Full Stack Web3 Developer</p>
                        <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>
                    </div>
                </div>
                <div className="flex flex-col gap-2">
                    <div className="flex items-center gap-1">
                        <HiOutlineMail/> 
                        <p>dineshaitham2@gmail.com</p>
                    </div>
                    <div className="flex items-center gap-1">
                        <FiPhone/>
                        <p>+918897230284</p>
                    </div>
                    <div className="flex items-center gap-1">
                        <button className="py-2 px-4 bg-[#1DA1F2] rounded-lg flex items-center gap-1 text-white"><FiTwitter/> Twitter</button>
                        <button className="py-2 px-4 bg-black rounded-lg flex items-center gap-1 text-white"><AiFillGithub/>Github</button>
                    </div>
                </div>
            </div>
            <div className="grid grid-cols-3 gap-8 pt-5 px-20">
                <div>
                    <p className="font-bold text-xl uppercase">Work Experience</p>
                    <div className="flex flex-col gap-1 mt-2">
                        <div className="flex flex-col gap-1">
                            <p className="font-bold text-lg">Full Stack Web3 Developer</p>
                            <p className="text-gray-600">Remote3</p>
                            <p className="text-gray-600">2021 - Present</p>
                        </div>
                        <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>
                    </div>
                    <div className="flex flex-col gap-1 mt-2">
                        <div className="flex flex-col gap-1">
                            <p className="font-bold text-lg">Full Stack Web3 Developer</p>
                            <p className="text-gray-600">Remote3</p>
                            <p className="text-gray-600">2021 - Present</p>
                        </div>
                        <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>
                    </div>
                    <div className="flex flex-col gap-1 mt-2">
                        <div className="flex flex-col gap-1">
                            <p className="font-bold text-lg">Full Stack Web3 Developer</p>
                            <p className="text-gray-600">Remote3</p>
                            <p className="text-gray-600">2021 - Present</p>
                        </div>
                        <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>
                    </div>
                </div>
                
                <div>
                    <p className="font-bold text-xl uppercase ">Projects</p>
                    <div className="flex flex-col gap-1 mt-2">
                        <div className="flex flex-col gap-1">
                            <div className="flex items-center gap-1 text-lg">
                                <p className="font-bold ">BlockState </p>
                                <button className=""><BiLinkExternal /></button>
                            </div>
                            <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>                            
                        </div>
                    </div>
                    <div className="flex flex-col gap-1 mt-2">
                        <div className="flex flex-col gap-1">
                            <div className="flex items-center gap-1 text-lg">
                                <p className="font-bold ">BlockState </p>
                                <button className=""><BiLinkExternal /></button>
                            </div>
                            <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>                            
                        </div>
                    </div>
                    <div className="flex flex-col gap-1 mt-2">
                        <div className="flex flex-col gap-1">
                            <div className="flex items-center gap-1 text-lg">
                                <p className="font-bold ">BlockState </p>
                                <button className=""><BiLinkExternal /></button>
                            </div>
                            <p className="text-gray-600">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero.</p>                            
                        </div>
                    </div>
                    <p className="font-bold text-xl uppercase mt-3">Skills</p>
                    <div className="grid grid-cols-4 grid-flow-row gap-1 mt-2">
                        {
                            skills.map(skill => {
                                return <div className="flex items-center gap-1" key="0">
                                    <div className="py-1 px-2 bg-gray-500 text-white rounded-md mt-1">{skill}</div>
                                </div>
                            })
                        }
                    </div>
                </div> 
                <div className="flex flex-col gap-4">
                    <div>
                        <p className="font-bold text-xl uppercase">Education</p>
                        <div>
                            <div className="flex flex-col gap-1 mt-2">
                                <p className="font-bold text-lg">Bachelor of Technology</p>
                                <p className="font-bold">Veltech University</p>
                                <p className="text-gray-600">06/2019 - 06/2023</p>
                            </div>    
                        </div>
                    </div>
                    <div>
                        <p className="font-bold text-xl uppercase">COMPETITIONS</p>
                        <div>
                            <div className="flex flex-col gap-1 mt-2">
                                <p className="font-bold text-lg">EthOnline</p>
                                <p className="text-gray-600">06/2023 - 06/2023</p>
                                <p className="text-gray-600 ">Won multiple bounties and pool prizes for my Block State project</p>
                            </div>
                        </div>
                        <div>
                            <div className="flex flex-col gap-1 mt-2">
                                <p className="font-bold text-lg">EthOnline</p>
                                <p className="text-gray-600">06/2023 - 06/2023</p>
                                <p className="text-gray-600 ">Won multiple bounties and pool prizes for my Block State project</p>
                            </div>
                        </div>
                        <div>
                            <div className="flex flex-col gap-1 mt-2">
                                <p className="font-bold text-lg">EthOnline</p>
                                <p className="text-gray-600">06/2023 - 06/2023</p>
                                <p className="text-gray-600 ">Won multiple bounties and pool prizes for my Block State project</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
